artifact_uri: remote_server_uri/1/b889178a0d4d484ebb6dba3fa558cb43/artifacts
end_time: 1622545213714
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b889178a0d4d484ebb6dba3fa558cb43
run_uuid: b889178a0d4d484ebb6dba3fa558cb43
source_name: ''
source_type: 4
source_version: ''
start_time: 1622545213597
status: 4
tags: []
user_id: DELL
