artifact_uri: remote_server_url/1/2a1df1178a924ecaaa86206efa9e7c5f/artifacts
end_time: 1622544899475
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 2a1df1178a924ecaaa86206efa9e7c5f
run_uuid: 2a1df1178a924ecaaa86206efa9e7c5f
source_name: ''
source_type: 4
source_version: ''
start_time: 1622544898742
status: 4
tags: []
user_id: DELL
